-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Dec 02, 2024 at 03:08 AM
-- Server version: 10.4.27-MariaDB
-- PHP Version: 8.1.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_kominfokelurahan`
--

-- --------------------------------------------------------

--
-- Table structure for table `sekolah`
--

CREATE TABLE `sekolah` (
  `id` int(11) NOT NULL,
  `nama_lokasi` varchar(255) NOT NULL,
  `link_maps` varchar(255) NOT NULL,
  `gambar` varchar(255) NOT NULL,
  `alamat` varchar(256) NOT NULL,
  `jarak` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `sekolah`
--

INSERT INTO `sekolah` (`id`, `nama_lokasi`, `link_maps`, `gambar`, `alamat`, `jarak`) VALUES
(1, 'Kec. Banyumanik, Kel. Gedawang', 'https://maps.app.goo.gl/ybUYkBJNcfjGsRdc8', '6743fc2feff41.jpg', 'JL. Haji Suradi, Gedawang, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50266', 15),
(2, 'Kec. Banyumanik, Kel. Pudakpayung', 'https://maps.app.goo.gl/uFQpR5oRjdSEoR8a7', '6743fc432ba50.jpg', 'Jalan Raya Setu No.4, Pudakpayung, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50265', 15),
(3, 'Kec. Banyumanik, Kel. Jabungan', 'https://maps.app.goo.gl/ks8TPXmytgTbDbC87', '6743fc56bc2b3.jpg', 'Jabungan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50266', 16),
(4, 'Kec. Banyumanik, Kel. Padangsari', 'https://maps.app.goo.gl/mHZrPUhbd5wtbb8x9', '6743fc7c0ec27.jpg', 'Jl Wisma Prasetya Barat No.1, Padangsari, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50266', 14),
(5, 'Kec. Banyumanik, Kel. Banyumanik', 'https://maps.app.goo.gl/DfxbVPRw6VB9LFqN8', '6743fc8f31683.jpg', 'Jl. Perintis Kemerdekaan, Banyumanik, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50264', 12),
(6, 'Kec. Banyumanik  Kel. Srondol Wetan', 'https://maps.app.goo.gl/J51DqesJmTTqAQnb7', '6743fcaa12cca.jpg', 'Jl. Bina Remaja No.39, Srondol Wetan, Banyumanik, Semarang City, Central Java 50263', 11),
(7, 'Kec. Banyumanik, Kel. Pedalangan', 'https://maps.app.goo.gl/r7RkA4mj9cmFt3jq8', '6743fcbce2272.jpg', 'Jl. Tusam Timur Raya No.30, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268', 13),
(8, 'Kec. Banyumanik, Kel. Sumurboto', 'https://maps.app.goo.gl/DPEoMbyNJQtyc3ca7', '6743fcca3959e.jpg', 'Sumurboto, Kota Semarang, Jawa Tengah', 10),
(9, 'Kec. Banyumanik, Kel. Srondol Kulon', 'https://maps.app.goo.gl/4ZsuE736t61XoWpm9', '6743fcd8e2c4b.jpg', 'Jl. Potrosari Tengah No.20, Srondol Kulon, Banyumanik, Semarang City, Central Java 50263', 11),
(10, 'Kec. Banyumanik, Kel. Tinjomoyo', 'https://maps.app.goo.gl/v5ojdqQTPcJxcKMZ8', '6743fd03afe47.jpg', 'Jl. Taman Teuku Umar No.1, Tinjomoyo, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50262', 7),
(11, 'Kec. Banyumanik, Kel. Ngesrep', 'https://maps.app.goo.gl/1dZcv52G3eBfSiWCA', '6743fd916de7a.jpg', 'Jl. Teuku Umar No.56, Ngesrep, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50262', 7),
(12, 'Kec. Candisari, Kel. Candi', 'https://maps.app.goo.gl/3YYdCHQHG5AvFQnG8', '6743fdffa49a1.jpg', 'Candi, Kec. Candisari, Kota Semarang, Jawa Tengah 50257', 5),
(13, 'Kec. Candisari,  Kel. Jatingaleh', 'https://maps.app.goo.gl/LnUVxRcZMK3CdqiH8', '6743fe333ecb0.jpg', 'JL. Jatingaleh No.3, Ngesrep, Banyumanik, Semarang City, Central Java 50261', 7),
(14, 'Kec. Candisari,  Kel. Jomblang', 'https://maps.app.goo.gl/iKjGCmhZWU4q3mnD7', '6743fe4cf0964.jpg', 'Jl. Cinde Dalam VII No.1, Jomblang, Candisari, Semarang City, Central Java 50256', 6),
(15, 'Kec. Candisari,  Kel. Kaliwiru', 'https://maps.app.goo.gl/FZmBiGAgWhv47PbQA', '6743fe687b650.jpg', 'Jl. Lompo Batang No.22, Kaliwiru, Kec. Candisari, Kota Semarang, Jawa Tengah 50253', 6),
(16, 'Kec. Candisari,  Kel. Karanganyar Gunung', 'https://maps.app.goo.gl/GQGRSVSiDymUfaYZ9', '6743fea766bac.jpg', 'Jl. Karanganyar Gn. No.204, Karanganyar Gunung, Candisari, Semarang City, Central Java 50255', 6),
(17, 'Kec. Candisari,  Kel. Tegalsari', 'https://maps.app.goo.gl/F7TJktskPZWZiHLN9', '6743feb5162f0.jpg', 'Jl. Genuksari No.1, Tegalsari, Kec. Candisari, Kota Semarang, Jawa Tengah 50117', 4),
(18, 'Kec. Candisari,  Kel. Wonotingal', 'https://maps.app.goo.gl/BTzz332gUvzvt5uf6', '6743ff03c72de.jpg', 'JL. Singgalang I No.1, Wonotingal, Candisari, Semarang City, Central Java 50252', 6),
(19, 'Kec. Gajahmungkur,  Kel. Bendan Duwur', 'https://maps.app.goo.gl/wRYE6YGR8GStcgnE7', '6743ff18396c5.jpg', 'Jl. Talangsari No.52, Bendan Duwur, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50235', 6),
(20, 'Kec. Gajahmungkur,  Kel. Bendan Ngisor', 'https://maps.app.goo.gl/92qRKdypEvjq4Q2TA', '6743ff272636b.jpg', 'Jl. Sampangan Baru Gg. V No.24 Blok. A, Bendan Ngisor, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50233', 4),
(21, 'Kec. Gajahmungkur,  Kel. Bendungan', 'https://maps.app.goo.gl/bc94xEZRF8b3QaV8A', '6743ff85bbb57.jpg', 'Bendungan, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah', 2),
(22, 'Kec. Gajahmungkur,  Kel. Gajahmungkur', 'https://maps.app.goo.gl/ZURe1BMbCCWVYLFU8', '6743ffb39e77d.jpg', 'Jl. Merapi No.2A, Gajahmungkur, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50232', 3),
(23, 'Kec. Gajahmungkur,  Kel. Karangrejo', 'https://maps.app.goo.gl/h58wevLyYH86B4SN8', '6743ffc37911e.jpg', 'Jl. Karangrejo Tengah No.19, Karangrejo, Gajahmungkur, Semarang City, Central Java 50231', 7),
(24, 'Kec. Gajahmungkur,  Kel. Lempongsari', 'https://maps.app.goo.gl/dKSU4LKngCc2cBkTA', '6743ffdc7c670.jpg', 'Jl. Lempongsari No.314 C, Lempongsari, Gajahmungkur, Semarang City, Central Java 50231', 2),
(25, 'Kec. Gajahmungkur,  Kel. Petompon', 'https://maps.app.goo.gl/bqoLFHzaQdrawAQdA', '674400326ebbc.jpg', 'Jl. Kelud Utara IV No.1, Petompon, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50237', 3),
(26, 'Kec. Gajahmungkur,  Kel. Sampangan', 'https://maps.app.goo.gl/rrvoRhBypyPknUrq6', '67440041dba5d.jpg', 'Jl. Menoreh Raya Jl. Raya Panjangan No.12, Sampangan, Gajahmungkur, Semarang City, Central Java 50232', 5),
(27, 'Kec. Gayamsari,  Kel. Gayamsari', 'https://maps.app.goo.gl/jfafqTLQa8icuJ1k8', '6744005273a95.jpg', 'Jl.Slamet Riyadi No.4, Gayamsari, Semarang City, Central Java 50161', 5),
(28, 'Kec. Gayamsari,  Kel. Kaligawe', 'https://maps.app.goo.gl/oauTRwZH5wwUsb6m8', '674400ceb8326.jpg', 'Jl. Sawah Besar. XIII, Kaligawe, Gayamsari, Semarang City, Central Java 50164', 6),
(29, 'Kec. Gayamsari,  Kel. Pandean Lamper', 'https://maps.app.goo.gl/mr1MNtcej5o4Daa89', '674400f12e87c.jpg', 'Pandean Lamper, Kec. Gayamsari, Kota Semarang, Jawa Tengah 50249', 6),
(30, 'Kec. Gayamsari,  Kel. Sambirejo', 'https://maps.app.goo.gl/vKK5L4bFLr4YgTab6', '674401015de84.jpg', 'Sambirejo, Gayamsari, Semarang City, Central Java 50166', 4),
(31, 'Kec. Gayamsari,  Kel. Sawah Besar', 'https://maps.app.goo.gl/eSnvTafNXb1qUZ9a6', '6744011007176.jpg', 'Jl. Tambak Dalam Raya No.37, Sawah Besar, Gayamsari, Semarang City, Central Java 50163', 6),
(32, 'Kec. Gayamsari,  Kel. Siwalan', 'https://maps.app.goo.gl/xSfC6A1wpFMCQqA3A', '674401700f9cd.jpg', 'Jl. Plewan II No.4, Siwalan, Kec. Gayamsari, Kota Semarang, Jawa Tengah 50162', 6),
(33, 'Kec. Gayamsari,  Kel. Tambakrejo', 'https://maps.app.goo.gl/4YyHTHnb2voBp9v18', '6744018269425.jpg', 'Jl. Purwosari 4 No.12, Tambakrejo, Gayamsari, Semarang City, Central Java 50174', 6),
(34, 'Kec. Genuk,  Kel. Bangetayu Kulon', 'https://maps.app.goo.gl/FLcA8LeCYmd7obAG8', '674401a01b730.jpg', 'Jl. Banget Prasetya V, Bangetayu Kulon, Kec. Genuk, Kota Semarang, Jawa Tengah 50115', 10),
(35, 'Kec. Genuk  Kel. Bangetayu Wetan', 'https://maps.app.goo.gl/pUwio1dmhgCri2obA', '674401c224ddf.jpg', 'Jl Raya Genuk Pedurungan, Bangetayu Kulon, Genuk, Bangetayu Wetan, Kec. Genuk, Kota Semarang, Jawa Tengah 50115', 11),
(36, 'Kec. Genuk  Kel. Banjardowo', 'https://maps.app.goo.gl/ZNGatGKTsWxQRDKZA', '674401deb4e5e.jpg', 'Jl. Ratan Cilik No.5, RT.06/RW.02, Banjardowo, Kec. Genuk, Kota Semarang, Jawa Tengah 50117', 10),
(37, 'Kec. Genuk  Kel. Gebangsari', 'https://maps.app.goo.gl/ASRg9vsLGxBUusTZA', '674401edc72ad.jpg', 'Jl. Widuri Krajan No.1, RT.02/RW.05, Gebangsari, Kec. Genuk, Kota Semarang, Jawa Tengah 50117', 9),
(38, 'Kec. Genuk  Kel. Genuksari', 'https://maps.app.goo.gl/VL6mGUqE9kjgy2iK7', '674401fc78f29.jpg', 'Jl. Genuksari No.1, Genuksari, Genuk, Semarang City, Central Java 50117', 10),
(39, 'Kec. Genuk, Kel. Karangroto', 'https://maps.app.goo.gl/xahbfonT5sfjPx7r8', '6745510bd8b28.png', ' Jl. Kyai H. Zainuddin Raya No.5, Karangroto, Kec. Genuk, Kota Semarang, Jawa Tengah 50117', 12),
(40, 'Kec. Genuk, Kel. Kudu', 'https://maps.app.goo.gl/cozpNhhAsTtffzFZA', '6745511d5234b.png', 'Jl. Kyai H. Zainuddin Raya No.5, Karangroto, Kec. Genuk, Kota Semarang, Jawa Tengah 50117', 13),
(41, 'Kec. Genuk, Kel. Muktiharjo Lor', 'https://maps.app.goo.gl/HLr3ohSEwuhPQtun7', '6745513270058.png', 'Muktiharjo Lor, Kec. Genuk, Kota Semarang, Jawa Tengah 50111', 7),
(42, 'Kec. Genuk, Kel. Penggaron Lor', 'https://maps.app.goo.gl/ERGBzFDwGVyt7ZpH6', '67455142e6069.png', 'Jl. Banjardowo Raya Jl. Kudu Raya No.02, Penggaron Lor, Kec. Genuk, Kota Semarang, Jawa Tengah 50113', 14),
(43, 'Kec. Genuk, Kel. Sembungharjo', 'https://maps.app.goo.gl/tRTjQ9wVEZCzGCy38', '674551580176f.png', 'Jl. Widoro Raya No.1, Sembungharjo, Kec. Genuk, Kota Semarang, Jawa Tengah 50116', 12),
(44, 'Kec. Genuk, Kel. Terboyo Kulon', 'https://maps.app.goo.gl/ttBgSQJSphGsXFS27', '6745516987731.png', 'Jl. Terboyo Kulon 1, Terboyo Kulon, Kec. Genuk, Kota Semarang, Jawa Tengah 50112', 7),
(45, 'Kec. Genuk, Kel. Terboyo Wetan', 'https://maps.app.goo.gl/UVuB6H7whnjavuNu8', '6745517ac3ab1.png', 'Jl. Terboyo Industri No.15A, Terboyo Wetan, Kec. Genuk, Kota Semarang, Jawa Tengah 50112', 8),
(46, 'Kec. Genuk, Kel. Trimulyo', 'https://maps.app.goo.gl/9i8GBfzG2G6uRcf27', '674551a7b536b.png', 'Jl. Trimulyo Raya, Trimulyo, Kec. Genuk, Kabupaten Demak, Jawa Tengah 50118', 9),
(47, 'Kec. Gunungpati,  Kel. Cepoko', 'https://maps.app.goo.gl/YJKdKtUpcT1EajBy9', '674551b9c8082.png', 'kp. Jetis, Cepoko, Gunung Pati, Semarang City, Central Java 50223', 15),
(48, 'Kec. Gunungpati, Kel. Gunungpati', 'https://maps.app.goo.gl/xsuLu1yEfyMHCyfS6', '674551cd0cd3d.png', 'Jl. Magersari, Gunungpati, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50229', 16),
(49, 'Kec. Gunungpati, Kel. Jatirejo', 'https://maps.app.goo.gl/8Yir7wrwGqfaT62Q6', '674551f00a350.png', 'Jatirejo, Gunung Pati, Jatirejo, Semarang, Kota Semarang, Jawa Tengah 50223', 14),
(50, 'Kec. Gunungpati, Kel. Kalisegoro', 'https://maps.app.goo.gl/AoyLpRnz4GuFyJz99', '6745520089545.png', 'Kalisegoro, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50229', 12),
(51, 'Kec. Gunungpati, Kel. Kandri', 'https://maps.app.goo.gl/1fhEdevqBEDJK5DV7', '674552120d75f.png', 'Jl. Kandri Utara II, Kandri, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50222', 13),
(52, 'Kec. Gunungpati, Kel. Mangunsari', 'https://maps.app.goo.gl/PqJBwmgGjE2i13Qg6', '6745522409ddb.png', 'Jl. Dukuh Mraggen, Mangunsari, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50227', 14),
(53, 'Kec. Gunungpati, Kel. Ngijo', 'https://maps.app.goo.gl/bM6Ln3UWHn612Aoz8', '6745523796645.png', 'Jl. Perum Mangunsari Asri, Ngijo, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50228', 13),
(54, 'Kec. Gunungpati, Kel. Nongkosawit', 'https://maps.app.goo.gl/bv3BsAwTCdh2bM4q7', '6745524953789.png', 'Nongkosawit, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50224', 14),
(55, 'Kec. Gunungpati, Kel. Pakintelan', 'https://maps.app.goo.gl/yE7nwVEyZR7YE5kf8', '67455277738de.png', 'Pakintelan, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50227', 15),
(56, 'Kec. Gunungpati, Kel. Patemon', 'https://maps.app.goo.gl/gGptRWSaemQYJiEU7', '6745528af104c.png', 'Gg. Bukit Asri No.61, Patemon, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50228', 12),
(57, 'Kec. Gunungpati, Kel. Plalangan', 'https://maps.app.goo.gl/jHcgh2KHJsYfgQu66', '674552a9dc915.png', 'Jl. Raya Plalangan, Plalangan, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50225', 15),
(58, 'Kec. Gunungpati, Kel. Pongangan', 'https://maps.app.goo.gl/nBJbQ1spHKkzxvBD7', '674552b973abf.png', 'Pongangan, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50229', 13),
(59, 'Kec. Gunungpati, Kel. Sadeng', 'https://maps.app.goo.gl/BzHjCMWBQXy9yjdb7', '674552cb591ac.png', 'Jl. Sadeng I No.1, Sadeng, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50222', 10),
(60, 'Kec. Gunungpati, Kel. Sekaran', 'https://maps.app.goo.gl/ZiKJMKsFeTJGVbHC8', '67455d5c10a5e.png', 'Sekaran, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50229', 10),
(61, 'Kec. Gunungpati, Kel. Sukorejo', 'https://maps.app.goo.gl/q6tMjRtddUicy1PS8', '67455d769ef41.png', 'Sukorejo, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50221', 8),
(62, 'Kec. Gunungpati, Kel. Sumurrejo', 'https://maps.app.goo.gl/hStFAj3FivZaZDN79', '67455db022eb3.png', 'Jalan Kayumas Timur, Sumurrejo, Gunung Pati, Semarang City, Central Java 50226', 17),
(63, 'Kec. Mijen, Kel. Bubakan', 'https://maps.app.goo.gl/oQGwYcyJJeb1XfNe7', '67455e52c61de.png', 'Bubakan, Kec. Mijen, Kota Semarang, Jawa Tengah 50216', 21),
(64, 'Kec. Mijen, Kel. Cangkiran', 'https://maps.app.goo.gl/nfxwYnnaRk9cKtAY7', '674845d9849ac.png', 'Jl. Raya Cangkiran No.21, Cangkiran, Kec. Mijen, Kota Semarang, Jawa Tengah 50216', 20),
(65, 'Kec. Mijen, Kel. Jatibarang', 'https://maps.app.goo.gl/EL3P8yL49CGz3cgw9', '6748463f0a42a.png', 'Jl. Jatibarang, Jatibarang, Kec. Mijen, Kota Semarang, Jawa Tengah 50219', 16),
(66, 'Kec. Mijen, Kel. Jatisari', 'https://maps.app.goo.gl/M1rWf96R88AMcVVR6', '6748467e2e488.png', 'Jatisari, Kec. Mijen, Kota Semarang, Jawa Tengah 50275', 19),
(67, 'Kec. Mijen, Kel. Karangmalang', 'https://maps.app.goo.gl/jm6THsgyssRkRdAJ7', '674846aa52a9e.png', 'Karangmalang, Kec. Mijen, Kota Semarang, Jawa Tengah 50216', 21),
(68, 'Kec. Mijen, Kel. Kedungpani', 'https://maps.app.goo.gl/2FcCT3Vxxwgq44ys6', '6748470353a0e.png', 'Jalan Panjangan Kedungpani, Kedungpane, Semarang, Kota Semarang, Jawa Tengah 50211', 14),
(69, 'Kec. Mijen, Kel. Mijen', 'https://maps.app.goo.gl/f97KnoqGkWH9ecqp7', '6748473d26f0e.png', 'Mijen, Kec. Mijen, Kota Semarang, Jawa Tengah 50519', 15),
(70, 'Kec. Mijen, Kel. Ngadirgo', 'https://maps.app.goo.gl/uVweH6JVSn9QThk9A', '67484757e9394.png', 'Jl. Raya Ngadirgo, Ngadirgo, Kec. Mijen, Kota Semarang, Jawa Tengah 50213', 18),
(71, 'Kec. Mijen, Kel. Pesantren', 'https://maps.app.goo.gl/Wrv7E7dbkTKZ8rm99', '674847ad8c967.png', ' Jl. Pesantren No.raya, Pesantren, Kec. Mijen, Kota Semarang, Jawa Tengah 50213', 15),
(72, 'Kec. Mijen, Kel. Polaman', 'https://maps.app.goo.gl/dkYqBbJA4FQEBwDW7', '674847efcd639.png', 'Jl. RM. Soebagiyono Tcondrokoesoemo No. 34, Polaman, Kec. Mijen, Kota Semarang, Jawa Tengah 50217', 21),
(73, 'Kec. Mijen, Kel. Purwosari', 'https://maps.app.goo.gl/zgNG9Qk76ndpwATU6', '6748482cd78c9.png', 'Jl. Patriot II Jl. Purwosari Perbalan V Gg. H No.231, Purwosari, Kec. Semarang Utara, Kota', 19),
(74, 'Kec. Mijen, Kel. Tambangan', 'https://maps.app.goo.gl/XoiYQy6SRrxt9AFh8', '6748486961b46.png', 'Jl. Rm. Hadisoebeno Sosro Wardoyo, Tambangan, Kec. Mijen, Kota Semarang, Jawa Tengah 50216', 19),
(75, 'Kec. Mijen, Kel. Wonolopo', 'https://maps.app.goo.gl/JpiBaJnrzr4S4kch6', '6748487bb6fa9.png', 'Wonolopo, Kec. Mijen, Kota Semarang, Jawa Tengah 50215', 16),
(76, 'Kec. Mijen, Kel. Wonoplumbon', 'https://maps.app.goo.gl/P6q81bG6ab5aejFC7', '6748489621084.png', 'Wonoplumbon, Kec. Mijen, Kota Semarang, Jawa Tengah 50214', 19),
(77, 'Kec. Mijen, Kel. Bambankerep', 'https://maps.app.goo.gl/6iH1WJZU5nacKbR4A', '67484a6899aae.jpg', 'Jl. Untung Suropati No.29, RT.04/RW.05, Bambankerep, Kec. Ngaliyan, Kota Semarang, Jawa Tengah 50211', 7),
(469, 'Kec. Ngaliyan, Kel. Bambankerep', 'https://maps.app.goo.gl/DuyzAdXv4GDvDNDx6', 'IMG-674a7c668176c5.43865136.jpg', 'Kantor Kelurahan BambanKerep, Jl. Untung Suropati No.29, RT.04/RW.05, Bambankerep, Ngaliyan, Semarang City, Central Java 50211', 8),
(470, 'Kec. Ngaliyan, Kel. Bringin', 'https://maps.app.goo.gl/UKypKY9zcKuNMaUR8', 'IMG-674a7ce136bb56.70316184.jpg', 'Jl. Beringin Raya I No.23 Kel, Bringin, Kec. Ngaliyan, Kota Semarang, Jawa Tengah 50189', 10),
(471, 'Kec. Ngaliyan, Kel. Gondoriyo', 'https://maps.app.goo.gl/KjZDUneMUdC1HXiX6', 'IMG-674a7d3353f9b0.34632509.png', 'Jl. Beringin Raya No.99, Bringin, Kec. Ngaliyan, Kota Semarang, Jawa Tengah 50189', 11),
(472, 'Kec. Ngaliyan, Kel. Kalipancur', 'https://maps.app.goo.gl/YKKApkjFXttv9K3HA', 'IMG-674a7da13646d2.17183413.png', 'Jl. Abdulrahman Saleh No.291, Kalipancur, Kec. Ngaliyan, Kota Semarang, Jawa Tengah 50183', 7),
(473, 'Kec. Ngaliyan, Kel. Ngaliyan', 'https://maps.app.goo.gl/G5SfzTofxTFUbnfEA', 'IMG-674a7df19a4097.60086577.png', '283X+C6G, Jalan Raya, Ngaliyan, Semarang City, Central Java 50181', 8),
(474, 'Kec. Ngaliyan, Kel. Podorejo', 'https://maps.app.goo.gl/biHdshaG217Qhw5W8', 'IMG-674a7e38375385.40440029.jpg', 'X7RR+MH6, Podorejo, Kec. Ngaliyan, Kota Semarang, Jawa Tengah 50187', 18),
(475, 'Kec. Ngaliyan, Kel. Purwoyoso', 'https://maps.app.goo.gl/CZR5nmJEpgvPvKBu7', 'IMG-674a7e7478aed4.05098859.png', '2967+HX4, Jl. Sriwidodo Utara 104, Purwoyoso, Kec. Ngaliyan, Kota Semarang, Jawa Tengah 50184', 6),
(476, 'Kec. Ngaliyan, Kel. Tambakaji', 'https://maps.app.goo.gl/ZRxcWwjKaJRebMR47', 'IMG-674a7eb6e167a5.49224189.jpg', '2982+RGP, Jalan Siliwangi, Tambakaji, Ngaliyan, Tambakaji, Semarang, Kota Semarang, Jawa Tengah 50185', 7),
(477, 'Kec. Ngaliyan, Kel. Wonosari', 'https://maps.app.goo.gl/HUFqEQcKpmofZZCN7', 'IMG-674a7f5b66fd83.47340805.png', 'Jl. Jend. Urip Sumoharjo, RT.01/RW.08, Wonosari, Kec. Ngaliyan, Kota Semarang, Jawa Tengah 50186', 12),
(478, 'Kec. Ngaliyan, Kel. Wates', 'https://maps.app.goo.gl/YS4B6vuNGmwUZaSU6', 'IMG-674a7f9e8cee82.05723458.png', 'X8MQ+674, Jl. Moch. Ichsan, Wates, Ngaliyan, Wates, Semarang, Kota Semarang, Jawa Tengah 50181', 11),
(479, 'Kec. Pedurungan, Kel. Gemah', 'https://maps.app.goo.gl/zHpkMCX5GWVZv1Q47', 'IMG-674a7fe8af1de2.81875610.jpg', 'Jl. Brigjen Sudiarto No.Km. 11, Gemah, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50246', 6),
(480, 'Kec. Pedurungan, Kel. Kalicari', 'https://maps.app.goo.gl/4WUNoin3akopYmVs6', 'IMG-674a8049428d86.87785575.png', 'Jl. Supriyadi No.20, Kalicari, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50198', 6),
(481, 'Kec. Pedurungan, Kel. Muktiharjo Kidul', 'https://maps.app.goo.gl/pxm2XBgqDoVoh2vP6', 'IMG-674a80a3be7825.31284788.jpg', 'Jl. Sidomukti I No.24A, Muktiharjo Kidul, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50197', 7),
(482, 'Kec. Pedurungan, Kel. Palebon', 'https://maps.app.goo.gl/tqb7FNgBiNY6ELNW6', 'IMG-674a80f988a706.04673135.jpg', 'XFV7+VR4, Jl. Panda Raya, Palebon, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50246', 7),
(483, 'Kec. Pedurungan, Kel. Pedurungan Kidul', 'https://maps.app.goo.gl/KDdoiCKCChFxWDuU7', 'IMG-674a819c6fe187.38434626.jpg', 'XFMF+C22, JL 7, Pedurungan Kidul, Pedurungan, Semarang City, Central Java 50192', 8),
(484, 'Kec. Pedurungan, Kel. Pedurungan Lor', 'https://maps.app.goo.gl/MdmNg7xkWDbDxmHq9', 'IMG-674a822e542523.65373287.jpg', 'XFRP+XVJ, Pedurungan Lor, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50192', 10),
(485, 'Kec. Pedurungan, Kel. Pedurungan Tengah', 'https://maps.app.goo.gl/7fD262rRGFq69bCW8', 'IMG-674a82f032d354.59972734.jpg', 'Jl. Majapahit No.442, Pedurungan Tengah, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50246', 7),
(486, 'Kec. Pedurungan, Kel. Penggaron Kidul', 'https://maps.app.goo.gl/yV5AMh3N8B4ekEFEA', 'IMG-674a8342e68087.03149069.jpeg', 'XFJQ+XJR, Plamongan Sari, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50194', 9),
(487, 'Kec. Pedurungan, Kel. Plamongansari', 'https://maps.app.goo.gl/ZzQn12urs3uPqyAr8', 'IMG-674a838f15bb53.96244147.jpg', 'XFGP+C8X, Jl. Plamongansari V, Plamongan Sari, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50193', 10),
(488, 'Kec. Pedurungan, Kel. TlogoMulyo', 'https://maps.app.goo.gl/qiKUBs3xvfyDLZjC8', 'IMG-674a83ec0242b5.58641222.jpg', '2F2H+GX5, Tlogomulyo, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50195', 9),
(489, 'Kec. Pedurungan, Kel. Tlogosari Kulon', 'https://maps.app.goo.gl/SowdP7Gnb86bJxe97', 'IMG-674a842d8d0724.63973155.png', 'Jl. Tlogosari Raya No.18, Tlogosari Kulon, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50196', 5),
(490, 'Kec. Pedurungan, Kel. Tlogosari Wetan', 'https://maps.app.goo.gl/jmZADgbrUiuWb6YH6', 'IMG-674a8466a8d467.31885853.jpg', 'Jl. Perum Dolog Lor No.1, Tlogosari Wetan, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50196', 7),
(491, 'Kec. Semarang Barat, Kel. Bojong Salaman', 'https://maps.app.goo.gl/XfnzwWZa52Fo6VaW8', 'IMG-674a84b3990526.37674393.jpg', 'Jl. Puspanjolo Barat Raya No.40, Bojongsalaman, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50141', 2),
(492, 'Kec. Semarang Barat, Kel. Bongsari', 'https://maps.app.goo.gl/GpAQ6Y1Gbx1PxRRA7', 'IMG-674a85072e4f81.09240994.png', 'Jl. Pamularsih Raya No.16, Bongsari, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50148', 2),
(493, 'Kec. Semarang Barat, Kel. Cabean', 'https://maps.app.goo.gl/3eK4s3ntuTPvYgGS9', 'IMG-674a85424e4853.37895650.png', 'Jl. Puspanjolo Barat Raya No.8, Cabean, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50141', 2),
(494, 'Kec. Semarang Barat, Kel. Gisikdrono', 'https://maps.app.goo.gl/5Y3kLiyGDKr2qC1JA', 'IMG-674a857a4d8788.92269717.jpg', '296Q+RRQ, Jl. Pamularsih Raya, Gisikdrono, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50149', 4),
(495, 'Kec. Semarang Barat, Kel. Kalibanteng Kidul', 'https://maps.app.goo.gl/f9upx858XFRLkqEZ8', 'IMG-674a8653e27047.04672924.jpg', 'Jl. Taman Sri Rejeki No.2A, Kalibanteng Kidul, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50149', 4),
(496, 'Kec. Semarang Barat, Kel. Kalibanteng Kulon', 'https://maps.app.goo.gl/L4jkdwixWHgpt7uM7', 'IMG-674a869742d741.05438114.png', '297J+947, Jl. Sri Kuncoro Raya, RT.02/RW.03, Kalibanteng Kulon, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50145', 4),
(497, 'Kec. Semarang Barat, Kel. Karangayu', 'https://maps.app.goo.gl/fvUNFjM9jHA4mvwz9', 'IMG-674a86d238c5f1.91064575.jpg', '299R+RCH, Jl. Anjasmoro Raya, Karangayu, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50149', 3),
(498, 'Kec. Semarang Barat, Kel. Kembangarum', 'https://maps.app.goo.gl/1W4PN11tXAe74dWF6', 'IMG-674a870ad40ae2.00037659.png', 'Jl. Abdulrahman Saleh No.231, Kalipancur, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50183', 5),
(499, 'Kec. Semarang Barat, Kel. Krapyak', 'https://maps.app.goo.gl/icEKguQB6WPm2jKE9', 'IMG-674a8746b6c8d1.51572012.png', '2978+QMC, Jl. Subali Raya, Krapyak, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50146', 6),
(500, 'Kec. Semarang Barat, Kel. Krobokan', 'https://maps.app.goo.gl/8K2WcSMfE2it3dut5', 'IMG-674a87da3d0268.13867159.png', '29FX+HCP, Jl. Wiroto Raya, Krobokan, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50141', 2),
(501, 'Kec. Semarang Barat, Kel. Manyaran', 'https://maps.app.goo.gl/48KdLhpFV4k42E6a8', 'IMG-674a8811ca7193.58921668.png', 'Jl. Simongan No.200, Manyaran, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50148', 4),
(502, 'Kec. Semarang Barat, Kel. Ngemplaksimongan', 'https://maps.app.goo.gl/19ZyZ5Q59TJaGn9v7', 'IMG-674a8849024e51.89822353.png', 'Jl. Simongan No.8/617, Manyaran, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50148', 4),
(503, 'Kec. Semarang Barat, Kel. Salamanmloyo', 'https://maps.app.goo.gl/VCxfJjC3McgUQyLx9', 'IMG-674a8896804f96.00353410.png', '298R+7XX, Salamanmloyo, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50149', 3),
(504, 'Kec. Semarang Barat, Kel. Tambakharjo', 'https://maps.app.goo.gl/6L5h4vC4jgBn489B6', 'IMG-674a88ce2da9c1.79103308.png', '29C8+M98, RT.03/RW.01, Tambakharjo, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50149', 7),
(505, 'Kec. Semarang Barat, Kel. Tawangmas', 'https://maps.app.goo.gl/bxXgkK36Uxers53B9', 'IMG-674a88ffda3b94.81750899.jpeg', 'Jl.Semarang Indah Blok C XXI No. 4, Tawangmas, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50144', 4),
(506, 'Kec. Semarang Barat, Kel. Tawangsari', 'https://maps.app.goo.gl/2wUFMXAY4eVxegUv9', 'IMG-674a8933582c38.36856829.png', '29GM+RJW, JL. Puri Anjasmoro, Tawangsari, Komplek Puri Anjasmoro, Semarang, Tawangsari, Semarang Barat, Semarang City, Central Java 50144', 5),
(518, 'Kec. Semarang Utara, Kel. Panggung Kidul ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/2CM4%2BJF2+Kantor+Kelurahan+Panggung+Kidul,+Jl.+Brotojoyo+V,+Plombokan,+Semarang+Utara,+Semarang+City,+', 'IMG-674af9ce67d4b1.47710772.png', 'Kantor Kelurahan Panggung Kidul, 2CM4+JF2, Jl. Brotojoyo V, Plombokan, Semarang Utara, Semarang City, Central Java 50171', 3),
(519, 'Kec. Semarang Utara, Kel. Panggung Lor  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Panggung+Lor,+Jl.+Kuala+Mas+Raya+No.41,+Panggung+Lor,+Semarang+Utara,+Semarang+City,+C', 'IMG-674af9ce6a7ee9.02245258.png', 'Kantor Kelurahan Panggung Lor, Jl. Kuala Mas Raya No.41, Panggung Lor, Semarang Utara, Semarang City, Central Java 50177', 5),
(520, 'Kec. Semarang Utara, Kel. Plombokan  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Plombokan,+Jl.+Brotojoyo+No.7,+Plombokan,+Kec.+Semarang+Utara,+Kota+Semarang,+Jawa+Ten', 'IMG-674af9ce6c2ca5.89917539.png', 'Kantor Kelurahan Plombokan, Jl. Brotojoyo No.7, Plombokan, Kec. Semarang Utara, Kota Semarang, Jawa Tengah 50171', 2),
(521, 'Kec. Semarang Utara, Kel. Purwosari  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Purwosari,+Jl.+Patriot+II+Jl.+Purwosari+Perbalan+V+Gg.+H+No.231,+Purwosari,+Kec.+Semar', 'IMG-674af9ce6e03c2.90409457.png', 'Kantor Kelurahan Purwosari, Jl. Patriot II Jl. Purwosari Perbalan V Gg. H No.231, Purwosari, Kec. Semarang Utara, Kota Semarang, Jawa Tengah 50172', 3),
(522, 'Kec. Semarang Utara, Kel. Tanjung Mas  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Tanjung+Mas,+2CQJ%2B469,+Jl.+Ronggowarsito+No.42,+Tj.+Mas,+Kec.+Semarang+Utara,+Kota+S', 'IMG-674af9ce6ff353.84792491.png', 'Kantor Kelurahan Tanjung Mas, 2CQJ+469, Jl. Ronggowarsito No.42, Tj. Mas, Kec. Semarang Utara, Kota Semarang, Jawa Tengah 50174', 5),
(523, 'Kec. Tembalang, Kel. Bulusan  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Bulusan,+Jl.+Gondang+Raya+No.68,+Bulusan,+Tembalang,+Semarang+City,+Central+Java+50277', 'IMG-674af9ce719fb0.91228091.png', 'Kantor Kelurahan Bulusan, Jl. Gondang Raya No.68, Bulusan, Tembalang, Semarang City, Central Java 50277', 14),
(524, 'Kec. Tembalang, Kel. Jangli', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Jangli,+Jl.+Gabeng+Raya,+Jangli,+Kec.+Tembalang,+Kota+Semarang,+Jawa+Tengah+50274/@-7.', 'IMG-674af9ce739750.82224752.png', 'Kantor Kelurahan Jangli, Jl. Gabeng Raya, Jangli, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274', 9),
(525, 'Kec. Tembalang, Kel. Kedungmundu  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Kedungmundu,+XFG6%2B5FW,+Jalan+Kedung+Mundu,+Sambiroto,+Tembalang,+Sambiroto,+Semarang', 'IMG-674af9ce757e84.34905234.png', 'Kantor Kelurahan Kedungmundu, XFG6+5FW, Jalan Kedung Mundu, Sambiroto, Tembalang, Sambiroto, Semarang, Kota Semarang, Jawa Tengah 50273', 9),
(526, 'Kec. Tembalang, Kel. Kramas  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Kramas,+Jl.+Mulawarman+Raya+No.Kelurahan,+Kramas,+Kec.+Tembalang,+Kota+Semarang,+Jawa+', 'IMG-674af9ce779859.07682296.png', 'Kantor Kelurahan Kramas, Jl. Mulawarman Raya No.Kelurahan, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278', 13),
(527, 'Kec. Tembalang, Kel. Mangunharjo  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Lurah+Manguharjo,+Jl.+Raya+Mangun+Harjo+No.Raya+No.+21,+Mangunharjo,+Kec.+Tembalang,+Kota+Semara', 'IMG-674af9ce793337.28074015.png', 'Kantor Lurah Manguharjo, Jl. Raya Mangun Harjo No.Raya No. 21, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272', 12),
(528, 'Kec. Tembalang, Kel. Meteseh  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Meteseh,+WFV7%2B9W6,+Jl.+Profesor+Suharso,+Meteseh,+Kec.+Tembalang,+Kota+Semarang,+Jaw', 'IMG-674afdb1563e24.75124456.png', 'Kantor Kelurahan Meteseh, WFV7+9W6, Jl. Profesor Suharso, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271', 13),
(529, 'Kec. Tembalang, Kel. Rowosari  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Rowosari,+WFHF%2BGJ7,+Rowosari,+Kec.+Tembalang,+Kota+Semarang,+Jawa+Tengah+50279/@-7.0', 'IMG-674afdb1592fe2.39322348.png', 'Kantor Kelurahan Rowosari, WFHF+GJ7, Rowosari, Kec. Tembalang, Kota Semarang, Jawa Tengah 50279', 16),
(530, 'Kec. Tembalang, Kel. Sambiroto  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Sambiroto,+Jalan+Candiroto+Raya+No.89,+Sambiroto,+Tembalang,+Sambiroto,+Semarang,+Kota', 'IMG-674afdb15b4554.40820349.png', 'Kantor Kelurahan Sambiroto, Jalan Candiroto Raya No.89, Sambiroto, Tembalang, Sambiroto, Semarang, Kota Semarang, Jawa Tengah 50276', 10),
(531, 'Kec. Tembalang, Kel. Sendangguwo  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/kelurahan+sendangguwo,+XFP3%2BVPH,+Jl.+Sendangguwo+Selatan,+Sendangguwo,+Tembalang,+Semarang+City,+Cent', 'IMG-674afdb15d3796.01353126.png', 'kelurahan sendangguwo, XFP3+VPH, Jl. Sendangguwo Selatan, Sendangguwo, Tembalang, Semarang City, Central Java 50273', 8),
(532, 'Kec. Tembalang, Kel. Sendangmulyo  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Sendangmulyo,+Jalan+Klipang,+Sendangmulyo,+Kec.+Tembalang,+Kota+Semarang,+Jawa+Tengah/', 'IMG-674afdb15f55d7.76894918.png', 'Kantor Kelurahan Sendangmulyo, WFXJ+F4Q, Jl. Klipang, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272', 14),
(533, 'Kec. Tembalang, Kel. Tandang  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Tandang,+Jalan+Raya+Kedung+Mundu,+No.+120+B,+Tandang,+Kec.+Tembalang,+Kota+Semarang,+J', 'IMG-674afdb1621272.11718706.png', 'Kantor Kelurahan Tandang, Jalan Raya Kedung Mundu, No. 120 B, Tandang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274', 9),
(534, 'Kec. Tembalang, Kel. Tembalang  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Tembalang,+Jl.+Banjarsari+No.35,+Tembalang,+Kec.+Tembalang,+Kota+Semarang,+Jawa+Tengah', 'IMG-674afdb16413f5.73794211.png', 'Kantor Kelurahan Tembalang, Jl. Banjarsari No.35, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275', 12),
(535, 'Kec. Tugu, Kel. Jerakah  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Jerakah,+2987%2BQG3,+Jrakah,+Kec.+Tugu,+Kota+Semarang,+Jawa+Tengah+50151/@-6.9838089,1', 'IMG-674afdb165ffc6.29467507.png', 'Kantor Kelurahan Jerakah, 2987+QG3, Jrakah, Kec. Tugu, Kota Semarang, Jawa Tengah 50151', 7),
(536, 'Kec. Tugu, Kel. Karanganyar  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Karanganyar,+28FJ%2BPRX,+Jl.+Karanganyar,+Karanganyar,+Tugu,+Semarang+City,+Central+Ja', 'IMG-674afdb167d7c0.97936700.png', 'Kantor Kelurahan Karanganyar, 28FJ+PRX, Jl. Karanganyar, Karanganyar, Tugu, Semarang City, Central Java 50152', 11),
(537, 'Kec. Tugu, Kel. Mangkang Kulon ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/KELURAHAN+MANGKANG+KULON,+27GX%2BP42,+Mangkang+Kulon,+Kec.+Tugu,+Kota+Semarang,+Jawa+Tengah+50155/@-6.9', 'IMG-674afdb169cd65.36864031.png', 'KELURAHAN MANGKANG KULON, 27GX+P42, Mangkang Kulon, Kec. Tugu, Kota Semarang, Jawa Tengah 50155', 15),
(538, 'Kec. Tugu, Kel. Mangkang Wetan  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Mangkang+Wetan,+Jl.+Lap.+Kalisasak+No.9,+Mangkang+Wetan,+Tugu,+Semarang+City,+Central+', 'IMG-674b051d1eec52.24370307.png', 'Kantor Kelurahan Mangkang Wetan, Jl. Lap. Kalisasak No.9, Mangkang Wetan, Tugu, Semarang City, Central Java 50156', 17),
(539, 'Kec. Tugu, Kel. Mangunharjo  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Mangunharjo,+28V7%2B463,+Mangunharjo,+Kec.+Tugu,+Kota+Semarang,+Jawa+Tengah+50154/@-6.', 'IMG-674b051d231712.21234106.png', 'Kantor Kelurahan Mangunharjo, 28V7+463, Mangunharjo, Kec. Tugu, Kota Semarang, Jawa Tengah 50154', 18),
(540, 'Kec. Tugu, Kel. Randu Garut  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Randu+Garut,+Jl.+Jend.+Urip+Sumoharjo+No.10,+Randu+Garut,+Kec.+Tugu,+Kota+Semarang,+Ja', 'IMG-674b051d24f8e9.89895812.png', 'Kantor Kelurahan Randu Garut, Jl. Jend. Urip Sumoharjo No.10, Randu Garut, Kec. Tugu, Kota Semarang, Jawa Tengah 50244', 13),
(541, 'Kec. Tugu, Kel. Tugurejo  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Tugurejo,+Jl.+Tugurejo+Tim.+XI+No.1,+Tugurejo,+Tugu,+Semarang+City,+Central+Java+50182', 'IMG-674b051d276ab0.60420256.png', 'Kantor Kelurahan Tugurejo, Jl. Tugurejo Tim. XI No.1, Tugurejo, Tugu, Semarang City, Central Java 50182', 10),
(542, 'Kec. Tugu', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Tugu,+Jl.+Walisongo+No.KM+10,+Tugurejo,+Kec.+Tugu,+Kota+Semarang,+Jawa+Tengah+50182/@-', 'IMG-674b051d2935c5.19173884.png', 'Kantor Kecamatan Tugu, Jl. Walisongo No.KM 10, Tugurejo, Kec. Tugu, Kota Semarang, Jawa Tengah 50182', 9),
(543, 'Kec. Banyumanik', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Banyumanik,+Jl.+Prof.+Soedarto+No.116,+Sumurboto,+Kec.+Banyumanik,+Kota+Semarang,+Jawa', 'IMG-674b051d2aa470.88078472.png', 'Kantor Kecamatan Banyumanik, Jl. Prof. Soedarto No.116, Sumurboto, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50269', 11),
(544, 'Kec. Candisari', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Candisari,+Jl.+Kesatrian+No.18,+Jatingaleh,+Kec.+Candisari,+Kota+Semarang,+Jawa+Tengah', 'IMG-674b051d2c40a6.50625013.png', 'Kantor Kecamatan Candisari, Jl. Kesatrian No.18, Jatingaleh, Kec. Candisari, Kota Semarang, Jawa Tengah 50254', 8),
(545, 'Kec. Gajah Mungkur', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Gajah+Mungkur,+Jl.+Letnan+Jenderal+S.+Parman+No.38+A,+Bendungan,+Kec.+Gajahmungkur,+Ko', 'IMG-674b051d2ddfe8.92431344.png', 'Kantor Kecamatan Gajah Mungkur, Jl. Letnan Jenderal S. Parman No.38 A, Bendungan, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50231', 3),
(546, 'Kec. Gayamsari', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Gayamsari,+Jl.Slamet+Riyadi+No.8,+Gayamsari,+Kec.+Gayamsari,+Kota+Semarang,+Jawa+Tenga', 'IMG-674b051d2fdc67.10388365.png', 'Kantor Kecamatan Gayamsari, Jl.Slamet Riyadi No.8, Gayamsari, Kec. Gayamsari, Kota Semarang, Jawa Tengah 50248', 6),
(547, 'Kec. Genuk', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Genuk,+Jl.+Dong+Biru+No.12,+Genuksari,+Kec.+Genuk,+Kota+Semarang,+Jawa+Tengah+50117/@-', 'IMG-674b051d3110a8.73114883.png', 'Kantor Kecamatan Genuk, Jl. Dong Biru No.12, Genuksari, Kec. Genuk, Kota Semarang, Jawa Tengah 50117', 11),
(548, 'Kec. Gunung Pati', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kecamatan+Gunungpati,+Jl.+Mr.+Wuryanto+No.KM+5,+Sumurrejo,+Kec.+Gn.+Pati,+Kota+Semarang,+Jawa+Tengah+50', 'IMG-674b07729ad147.55315737.png', 'Kecamatan Gunungpati, Jl. Mr. Wuryanto No.KM 5, Sumurrejo, Kec. Gn. Pati, Kota Semarang, Jawa Tengah 50226', 17),
(549, 'Kec. Mijen ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Mijen,+Jl.+Raya+Semarang-Boja+No.122,+Wonolopo,+Kec.+Mijen,+Kota+Semarang,+Jawa+Tengah', 'IMG-674b07729c7ab1.75613890.png', 'Kantor Kecamatan Mijen, Jl. Raya Semarang-Boja No.122, Wonolopo, Kec. Mijen, Kota Semarang, Jawa Tengah 50215', 19),
(550, 'Kec. Ngaliyan ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Ngaliyan,+Jl.+Raya+Ngaliyan+No.234,+Ngaliyan,+Kec.+Ngaliyan,+Kota+Semarang,+Jawa+Tenga', 'IMG-674b07729e5284.89339991.png', 'Kantor Kecamatan Ngaliyan, Jl. Raya Ngaliyan No.234, Ngaliyan, Kec. Ngaliyan, Kota Semarang, Jawa Tengah 50181', 9),
(551, 'Kec. Pedurungan  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Pedurungan,+Jl.+Majapahit+No.357,+Gemah,+Pedurungan,+Semarang+City,+Central+Java+50191', 'IMG-674b07729fe916.49407549.png', 'Kantor Kecamatan Pedurungan, Jl. Majapahit No.357, Gemah, Pedurungan, Semarang City, Central Java 50191', 8),
(552, 'Kec. Semarang Barat  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Semarang+Barat,+Jl.+Ronggolawe+No.2,+Gisikdrono,+Kec.+Semarang+Barat,+Kota+Semarang,+J', 'IMG-674b0772a17321.09001820.png', 'Kantor Kecamatan Semarang Barat, Jl. Ronggolawe No.2, Gisikdrono, Kec. Semarang Barat, Kota Semarang, Jawa Tengah 50149', 4),
(553, 'Kec. Semarang Selatan  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Semarang+Selatan,+Jl.+Taman+Sompok+No.1,+Lamper+Lor,+Kec.+Semarang+Sel.,+Kota+Semarang', 'IMG-674b0772a2c146.79382042.png', 'Kantor Kecamatan Semarang Selatan, Jl. Taman Sompok No.1, Lamper Lor, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50249', 5),
(554, 'Kec. Semarang Tengah ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Semarang+Tengah,+Jl.+Taman+Seteran+Barat+No.1,+Miroto,+Kec.+Semarang+Tengah,+Kota+Sema', 'IMG-674b0772a47209.77332238.png', 'Kantor Kecamatan Semarang Tengah, Jl. Taman Seteran Barat No.1, Miroto, Kec. Semarang Tengah, Kota Semarang, Jawa Tengah 50134', 1),
(555, 'Kec. Semarang Timur  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Semarang+Timur,+Jl.+Barito+No.5,+Karangtempel,+Kec.+Semarang+Tim.,+Kota+Semarang,+Jawa', 'IMG-674b0772a5eff2.33147915.png', 'Kantor Kecamatan Semarang Timur, Jl. Barito No.5, Karangtempel, Kec. Semarang Tim., Kota Semarang, Jawa Tengah 50232', 4),
(556, 'Kec. Semarang Utara  ', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Semarang+Utara,+Jl.+Taman+Brotojoyo+No.2,+RT.005,+Panggung+Kidul,+Semarang+Utara,+Sema', 'IMG-674b0772a76710.88083440.png', 'Kantor Kecamatan Semarang Utara, Jl. Taman Brotojoyo No.2, RT.005, Panggung Kidul, Semarang Utara, Semarang City, Central Java 50178', 4),
(557, 'Kec. Tembalang', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kecamatan+Tembalang,+Jl.+Kol+H+Iman+Soeparto+No.+1,+Bulusan,+Tembalang,+Bulusan,+Kec.+Tembalang,', 'IMG-674b0772a90da1.54865986.png', 'Kantor Kecamatan Tembalang, Jl. Kol H Iman Soeparto No. 1, Bulusan, Tembalang, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277', 14),
(469, 'KELURAHAN BARUSARI', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kantor+Kelurahan+Barusari,+Jl.+Lemah+Gempal+VI+A+No.1,+Barusari,+Semarang+Selatan,+Semarang+City,+Cent', 'IMG-674b16b1e92622.36496331.png', 'Kantor Kelurahan Barusari, Jl. Lemah Gempal VI A No.1, Barusari, Semarang Selatan, Semarang City, Central Java 50245', 2),
(470, 'KELURAHAN BULUSTALAN', 'https://www.google.com/maps/dir/Dinas+Kominfo+Kota+Semarang,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Bulustalan,+Jl.+Bojong+Stalan+No.307,+RT.003%2FRW.003,+Bulustalan,+Semarang+Selatan,+Semarang+City,+Central+Java+50241/@-6.9830379,110.3984877', 'IMG-674b1a31906e78.94676372.png', 'Kantor Kelurahan Bulustalan', 2),
(471, 'KELURAHAN LAMPER KIDUL', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Central+Java/Kelurahan+Lamper+Kidul,+Jl.+Durian+Barat+No.31,+Kel,+Lamper+Kidul,+Kec.+Semarang+Sel.,+Kota+Semarang,+', 'IMG-674b1a8930b9d7.79583631.png', 'Kelurahan Lamper Kidul', 5),
(472, 'KELURAHAN LAMPER LOR', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kantor+Kelurahan+Lamper+Lor,+Jl.+Cempedak+Raya+No.8,+Lamper+Lor,+Semarang+Selatan,+Semarang+City,+Cent', 'IMG-674b1ae03b9fa1.60180966.png', 'Kantor Kelurahan Lamper Lor', 12),
(473, 'KELURAHAN LAMPER TENGAH', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kantor+Kelurahan+Lamper+Tengah,+Jl.+Nanas+No.8,+Lamper+Tengah,+Semarang+Selatan,+Semarang+City,+Centra', 'IMG-674b1b37b0c6e5.05893022.png', 'Kantor Kelurahan Lamper Tengah', 5),
(474, 'KELURAHAN MUGASSARI', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/2C58%2BCG6+Kelurahan+Mugassari+Semarang,+Mugassari,+Semarang,+Semarang+City,+Central+Java+50249/@-6.98', 'IMG-674b1bb91240e0.67508976.png', 'Kantor Kelurahan Mugassari', 1),
(475, 'KELURAHAN PETERONGAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kantor+Kelurahan+Peterongan,+Jl.+Pandean+Lamper+II+No.29,+Peterongan,+Semarang+Selatan,+Semarang+City,', 'IMG-674b1c22e66c53.87334005.png', 'Kantor Kelurahan Peterongan', 3),
(476, 'KELURAHAN PLEBURAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kantor+Kelurahan+Pleburan,+Jalan+Kartanegara+Selatan+II+No.11,+Jl.+Pleburan+Barat+No.50,+Pleburan,+Kec', 'IMG-674b1c736a0291.34817854.png', 'Kantor Kelurahan Pleburan', 3),
(477, 'KELURAHAN RANDUSARI', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/2C76%2B7M5+Kantor+Kelurahan+Randusari+Semarang,+Randusari,+Semarang+Selatan,+Semarang+City,+Central+Ja', 'IMG-674b1cb1ce1888.48479390.png', 'Kantor Kelurahan Randusari', 3),
(478, 'KELURAHAN WONODRI', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Wonodri,+Jl.+Wonodri+I+No.1,+Wonodri,+Kec.+Semarang+Sel.,+Kota+Semarang,+Jawa+Tengah+5', 'IMG-674b1d60308c27.97645678.png', 'Kantor Kelurahan Wonodri', 4),
(479, 'KELURAHAN BANGUNHARJO', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Bangunharjo,+Jl.+Jonegaran+No.310,+RT.005,+Bangunharjo,+Semarang+Tengah,+Semarang+City', 'IMG-674b1da6af4f91.28212642.png', 'Kantor Kelurahan Bangunharjo', 2),
(480, 'KELURAHAN BRUMBUNGAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/2C8G%2BHPC+Kantor+Kelurahan+Brumbungan,+Jl.+Widosari+Raya,+Miroto,+Semarang+Tengah,+Semarang+City,+Cent', 'IMG-674b1e0100c363.84648755.png', 'Kantor Kelurahan Brumbungan', 2),
(481, 'KELURAHAN GABAHAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Gabahan,+Jl.+Karang+Anyar+No.586,+Gabahan,+Semarang+Tengah,+Semarang+City,+Central+Jav', 'IMG-674b1e365e3189.02873315.png', 'Kantor Kelurahan Gabahan', 2),
(482, 'KELURAHAN JAGALAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kelurahan+Jagalan,+2CCH%2B5M2,+Jl.+Ki+Mangunsarkoro,+Jagalan,+Kec.+Semarang+Tengah,+Kota+Semarang,+Jawa', '674b1ef455d3e.png', 'Kantor Kelurahan Jagalan', 3),
(483, 'KELURAHAN KARANG KIDUL', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Karangkidul,+Jl.+Seroja+Barat+No.1,+Karangkidul,+Semarang+Tengah,+Semarang+City,+Centr', 'IMG-674b1f5d478502.54777921.png', 'Kantor Kelurahan Karangkidul', 2),
(484, 'KELURAHAN KAUMAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/2CGF%2B68F+Kelurahan+Kauman,+Jl.+Kauman+Pompa,+Kauman,+Kec.+Semarang+Tengah,+Kota+Semarang,+Jawa+Tengah', 'IMG-674b1fd2225aa1.38836624.png', 'Kantor Kelurahan Kauman', 2),
(485, 'KELURAHAN KEMBANGSARI', 'https://www.google.com/maps/dir/Dinas+Kominfo+Kota+Semarang,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Kembangsari,+Jl.+Prembaen+No.945,+Kembangsari,+Semarang+Tengah,+Semarang+City,+Central+Java+50133/@-6.9819417,110.4146679,18z/data=!3m1!4b1!4m', 'IMG-674b202d377d96.95048344.png', 'Kantor Kelurahan Kembangsari', 1),
(486, 'KELURAHAN KRANGGAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kranggan+Sub-District+Office,+Gg.+Pinggir+No.93+A,+Kranggan,+Semarang+Tengah,+Semarang+City,+Central+J', 'IMG-674b21dd3761c4.60460412.png', 'Kantor Kelurahan Kranggan', 2),
(487, 'KELURAHAN MIROTO', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Miroto+Subdistrict+Office,+Jl.+Seteran+Utara+No.7-9,+Miroto,+Semarang+Tengah,+Semarang+City,+Central+J', 'IMG-674b221df27008.68048563.png', 'Kantor Kelurahan Miroto', 1),
(488, 'KELURAHAN PANDANSARI', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kelurahan+PANDANSARI,+Jalan+No.3,+Pandansari,+Kec.+Semarang+Tengah,+Kota+Semarang,+Jawa+Te', 'IMG-674b23222c60a3.72647051.png', 'Kantor Kelurahan Pandansari', 2),
(489, 'KELURAHAN PEKUNDEN', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Pekunden,+Ktr.+Kelurahan+Pekunden,+Jl.+Taman+Pekunden+Tim.+No.38,+Pekunde', 'IMG-674b2365e226c2.75726137.png', 'Kantor Kelurahan Pekunden', 1),
(490, 'KELURAHAN PINDRIKAN KIDUL', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/2C95%2BFJQ+Kelurahan+Pendrikan+Kidul,+Pendrikan+Kidul,+Semarang+Tengah,+Semarang+City,+Cen', 'IMG-674b23acb1e032.87705241.png', 'Kelurahan Pendrikan Kidul', 1),
(491, 'KELURAHAN PINDRIKAN LOR', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kelurahan+Pendrikan+Lor,+Jl.+Indraprasta+No.5,+Pindrikan+Lor,+Kec.+Semarang+Tengah,+Kota+S', 'IMG-674b243b4d74e8.02764088.png', 'Kelurahan Pendrikan Lor', 2),
(492, 'KELURAHAN PURWODINATAN', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Purwodinatan,+Jl.+K.H.+Agus+Salim+No.7,+Purwodinatan,+Semarang+Tengah,+Se', 'IMG-674b24855023d7.75068236.png', 'Kantor Kelurahan Purwodinatan', 3),
(493, 'KELURAHAN SEKAYU', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Sekayu,+Jl.+Bedagan+Raya+No.465,+Sekayu,+Semarang+Tengah,+Semarang+City,+', 'IMG-674b24bb3b6142.09218242.png', 'Kantor Kelurahan Sekayu', 1);
INSERT INTO `sekolah` (`id`, `nama_lokasi`, `link_maps`, `gambar`, `alamat`, `jarak`) VALUES
(494, 'KELURAHAN BUGANGAN', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Bugangan,+Jl.+Citandui+Selatan+No.30,+Bugangan,+Semarang+Timur,+Semarang+', 'IMG-674b24e6884e44.68099099.png', 'Kantor Kelurahan Bugangan', 4),
(495, 'KELURAHAN KARANGTEMPEL', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Karang+Tempel,+Jl.+Hawa+Raya+No.9+A,+Karangtempel,+Semarang+Timur,+Semara', 'IMG-674b25147e03c1.26199682.png', 'Kantor Kelurahan Karang Tempel', 3),
(496, 'KELURAHAN KARANGTURI', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/2C7M%2B262+Kantor+Kelurahan+Karangturi,+Jl.+Kampung+Baris,+Karangturi,+Kec.+Semarang+Tim.,', 'IMG-674b2543f0cd37.00042956.png', 'Kantor Kelurahan Karangturi', 3),
(497, 'KELURAHAN KEBONAGUNG', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/2CHJ%2B4HF+Kantor+Kelurahan+Kebun+Agung,+Jl.+Kp.+Utri,+Kebonagung,+Semarang+Timur,+Semaran', 'IMG-674b257a9a2be9.21559012.png', 'Kantor Kelurahan Kebun Agung', 3),
(498, 'KELURAHAN KEMIJEN', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Kemijen,+Ktr.+Kelurahan+Kemijen,+Jl.+Penjaringan+I+No.1,+Kemijen,+Semaran', 'IMG-674b25a7210bf5.62681332.png', 'Kantor Kelurahan Kemijen', 5),
(499, 'KELURAHAN MLATIBARU', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Mlatibaru,+Jl.+Mlatiharjo+Raya+No.16,+Mlatibaru,+Semarang+Timur,+Semarang', 'IMG-674b25da477021.73468549.png', 'Kantor Kelurahan Mlatibaru', 5),
(500, 'KELURAHAN MLATIHARJO', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Mlatiharjo,+Jl.+Citandui+Raya+III+No.2,+Mlatiharjo,+Semarang+Timur,+Semar', 'IMG-674b2605d94b67.15240596.png', 'Kantor Kelurahan Mlatiharjo', 5),
(501, 'KELURAHAN REJOMULYO', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Rejomulyo,+Jl.+Raden+Patah+No.176A,+Rejomulyo,+Semarang+Timur,+Semarang+C', 'IMG-674b26406cfec4.83182531.png', 'Kantor Kelurahan Rejomulyo', 5),
(502, 'KELURAHAN REJOSARI', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Rejosari,+Jl.+Kridangga+Raya+No.1,+Rejosari,+Semarang+Timur,+Semarang+Cit', 'IMG-674b2685e43860.47063017.png', 'Kantor Kelurahan Rejosari', 3),
(503, 'KELURAHAN SARIREJO', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/2C8M%2BH67+Kantor+Kelurahan+Sarirejo,+Jl.+Karangsono,+Sarirejo,+Kec.+Semarang+Tim.,+Kota+S', 'IMG-674b26c2cec8f6.83144254.png', 'Kantor Kelurahan Sarirejo', 2),
(504, 'KELURAHAN BANDARHARJO', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Bandarharjo,+Jl.+Bandarharjo+Selatan+Timur+No.17,+Bandarharjo,+Semarang+U', 'IMG-674b276c4c7710.03911079.png', 'Kantor Kelurahan Bandarharjo', 3),
(505, 'KELURAHAN BULU LOR', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Bulu+Lor,+Jl.+Surtikanti+No.27+B,+Bulu+Lor,+Kec.+Semarang+Utara,+Kota+Sem', 'IMG-674b28294354b5.36028212.png', 'Kantor Kelurahan Bulu Lor', 2),
(506, 'KELURAHAN DADAPSARI', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Dadapsari,+Jl.+Kakap+No.72,+Dadapsari,+Kec.+Semarang+Utara,+Kota+Semarang', 'IMG-674b288081f4d0.26566903.png', 'Kantor Kelurahan Dadapsari', 3),
(507, 'KELURAHAN BARUSARI', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kantor+Kelurahan+Barusari,+Jl.+Lemah+Gempal+VI+A+No.1,+Barusari,+Semarang+Selatan,+Semarang+City,+Cent', 'IMG-674b16b1e92622.36496331.png', 'Kantor Kelurahan Barusari, Jl. Lemah Gempal VI A No.1, Barusari, Semarang Selatan, Semarang City, Central Java 50245', 2),
(508, 'KELURAHAN BULUSTALAN', 'https://www.google.com/maps/dir/Dinas+Kominfo+Kota+Semarang,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Bulustalan,+Jl.+Bojong+Stalan+No.307,+RT.003%2FRW.003,+Bulustalan,+Semarang+Selatan,+Semarang+City,+Central+Java+50241/@-6.9830379,110.3984877', 'IMG-674b1a31906e78.94676372.png', 'Kantor Kelurahan Bulustalan', 2),
(509, 'KELURAHAN LAMPER KIDUL', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Central+Java/Kelurahan+Lamper+Kidul,+Jl.+Durian+Barat+No.31,+Kel,+Lamper+Kidul,+Kec.+Semarang+Sel.,+Kota+Semarang,+', 'IMG-674b1a8930b9d7.79583631.png', 'Kelurahan Lamper Kidul', 5),
(510, 'KELURAHAN LAMPER LOR', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kantor+Kelurahan+Lamper+Lor,+Jl.+Cempedak+Raya+No.8,+Lamper+Lor,+Semarang+Selatan,+Semarang+City,+Cent', 'IMG-674b1ae03b9fa1.60180966.png', 'Kantor Kelurahan Lamper Lor', 12),
(511, 'KELURAHAN LAMPER TENGAH', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kantor+Kelurahan+Lamper+Tengah,+Jl.+Nanas+No.8,+Lamper+Tengah,+Semarang+Selatan,+Semarang+City,+Centra', 'IMG-674b1b37b0c6e5.05893022.png', 'Kantor Kelurahan Lamper Tengah', 5),
(512, 'KELURAHAN MUGASSARI', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/2C58%2BCG6+Kelurahan+Mugassari+Semarang,+Mugassari,+Semarang,+Semarang+City,+Central+Java+50249/@-6.98', 'IMG-674b1bb91240e0.67508976.png', 'Kantor Kelurahan Mugassari', 1),
(513, 'KELURAHAN PETERONGAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kantor+Kelurahan+Peterongan,+Jl.+Pandean+Lamper+II+No.29,+Peterongan,+Semarang+Selatan,+Semarang+City,', 'IMG-674b1c22e66c53.87334005.png', 'Kantor Kelurahan Peterongan', 3),
(514, 'KELURAHAN PLEBURAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kantor+Kelurahan+Pleburan,+Jalan+Kartanegara+Selatan+II+No.11,+Jl.+Pleburan+Barat+No.50,+Pleburan,+Kec', 'IMG-674b1c736a0291.34817854.png', 'Kantor Kelurahan Pleburan', 3),
(515, 'KELURAHAN RANDUSARI', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/2C76%2B7M5+Kantor+Kelurahan+Randusari+Semarang,+Randusari,+Semarang+Selatan,+Semarang+City,+Central+Ja', 'IMG-674b1cb1ce1888.48479390.png', 'Kantor Kelurahan Randusari', 3),
(516, 'KELURAHAN WONODRI', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Wonodri,+Jl.+Wonodri+I+No.1,+Wonodri,+Kec.+Semarang+Sel.,+Kota+Semarang,+Jawa+Tengah+5', 'IMG-674b1d60308c27.97645678.png', 'Kantor Kelurahan Wonodri', 4),
(517, 'KELURAHAN BANGUNHARJO', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Bangunharjo,+Jl.+Jonegaran+No.310,+RT.005,+Bangunharjo,+Semarang+Tengah,+Semarang+City', 'IMG-674b1da6af4f91.28212642.png', 'Kantor Kelurahan Bangunharjo', 2),
(518, 'KELURAHAN BRUMBUNGAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/2C8G%2BHPC+Kantor+Kelurahan+Brumbungan,+Jl.+Widosari+Raya,+Miroto,+Semarang+Tengah,+Semarang+City,+Cent', 'IMG-674b1e0100c363.84648755.png', 'Kantor Kelurahan Brumbungan', 2),
(519, 'KELURAHAN GABAHAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Gabahan,+Jl.+Karang+Anyar+No.586,+Gabahan,+Semarang+Tengah,+Semarang+City,+Central+Jav', 'IMG-674b1e365e3189.02873315.png', 'Kantor Kelurahan Gabahan', 2),
(520, 'KELURAHAN JAGALAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kelurahan+Jagalan,+2CCH%2B5M2,+Jl.+Ki+Mangunsarkoro,+Jagalan,+Kec.+Semarang+Tengah,+Kota+Semarang,+Jawa', '674b1ef455d3e.png', 'Kantor Kelurahan Jagalan', 3),
(521, 'KELURAHAN KARANG KIDUL', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Karangkidul,+Jl.+Seroja+Barat+No.1,+Karangkidul,+Semarang+Tengah,+Semarang+City,+Centr', 'IMG-674b1f5d478502.54777921.png', 'Kantor Kelurahan Karangkidul', 2),
(522, 'KELURAHAN KAUMAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Kota+Semarang,+Jawa+Tengah/2CGF%2B68F+Kelurahan+Kauman,+Jl.+Kauman+Pompa,+Kauman,+Kec.+Semarang+Tengah,+Kota+Semarang,+Jawa+Tengah', 'IMG-674b1fd2225aa1.38836624.png', 'Kantor Kelurahan Kauman', 2),
(523, 'KELURAHAN KEMBANGSARI', 'https://www.google.com/maps/dir/Dinas+Kominfo+Kota+Semarang,+Sekayu,+Kota+Semarang,+Jawa+Tengah/Kantor+Kelurahan+Kembangsari,+Jl.+Prembaen+No.945,+Kembangsari,+Semarang+Tengah,+Semarang+City,+Central+Java+50133/@-6.9819417,110.4146679,18z/data=!3m1!4b1!4m', 'IMG-674b202d377d96.95048344.png', 'Kantor Kelurahan Kembangsari', 1),
(524, 'KELURAHAN KRANGGAN', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Kranggan+Sub-District+Office,+Gg.+Pinggir+No.93+A,+Kranggan,+Semarang+Tengah,+Semarang+City,+Central+J', 'IMG-674b21dd3761c4.60460412.png', 'Kantor Kelurahan Kranggan', 2),
(525, 'KELURAHAN MIROTO', 'https://www.google.com/maps/dir/Dinas+Komunikasi,+Informatika,+Statistik+dan+Persandian+Kota+Semarang,+Jalan+Pemuda,+Sekayu,+Semarang+City,+Central+Java/Miroto+Subdistrict+Office,+Jl.+Seteran+Utara+No.7-9,+Miroto,+Semarang+Tengah,+Semarang+City,+Central+J', 'IMG-674b221df27008.68048563.png', 'Kantor Kelurahan Miroto', 1),
(526, 'KELURAHAN PANDANSARI', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kelurahan+PANDANSARI,+Jalan+No.3,+Pandansari,+Kec.+Semarang+Tengah,+Kota+Semarang,+Jawa+Te', 'IMG-674b23222c60a3.72647051.png', 'Kantor Kelurahan Pandansari', 2),
(527, 'KELURAHAN PEKUNDEN', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Pekunden,+Ktr.+Kelurahan+Pekunden,+Jl.+Taman+Pekunden+Tim.+No.38,+Pekunde', 'IMG-674b2365e226c2.75726137.png', 'Kantor Kelurahan Pekunden', 1),
(528, 'KELURAHAN PINDRIKAN KIDUL', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/2C95%2BFJQ+Kelurahan+Pendrikan+Kidul,+Pendrikan+Kidul,+Semarang+Tengah,+Semarang+City,+Cen', 'IMG-674b23acb1e032.87705241.png', 'Kelurahan Pendrikan Kidul', 1),
(529, 'KELURAHAN PINDRIKAN LOR', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kelurahan+Pendrikan+Lor,+Jl.+Indraprasta+No.5,+Pindrikan+Lor,+Kec.+Semarang+Tengah,+Kota+S', 'IMG-674b243b4d74e8.02764088.png', 'Kelurahan Pendrikan Lor', 2),
(530, 'KELURAHAN PURWODINATAN', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Purwodinatan,+Jl.+K.H.+Agus+Salim+No.7,+Purwodinatan,+Semarang+Tengah,+Se', 'IMG-674b24855023d7.75068236.png', 'Kantor Kelurahan Purwodinatan', 3),
(531, 'KELURAHAN SEKAYU', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Sekayu,+Jl.+Bedagan+Raya+No.465,+Sekayu,+Semarang+Tengah,+Semarang+City,+', 'IMG-674b24bb3b6142.09218242.png', 'Kantor Kelurahan Sekayu', 1),
(532, 'KELURAHAN BUGANGAN', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Bugangan,+Jl.+Citandui+Selatan+No.30,+Bugangan,+Semarang+Timur,+Semarang+', 'IMG-674b24e6884e44.68099099.png', 'Kantor Kelurahan Bugangan', 4),
(533, 'KELURAHAN KARANGTEMPEL', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Karang+Tempel,+Jl.+Hawa+Raya+No.9+A,+Karangtempel,+Semarang+Timur,+Semara', 'IMG-674b25147e03c1.26199682.png', 'Kantor Kelurahan Karang Tempel', 3),
(534, 'KELURAHAN KARANGTURI', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/2C7M%2B262+Kantor+Kelurahan+Karangturi,+Jl.+Kampung+Baris,+Karangturi,+Kec.+Semarang+Tim.,', 'IMG-674b2543f0cd37.00042956.png', 'Kantor Kelurahan Karangturi', 3),
(535, 'KELURAHAN KEBONAGUNG', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/2CHJ%2B4HF+Kantor+Kelurahan+Kebun+Agung,+Jl.+Kp.+Utri,+Kebonagung,+Semarang+Timur,+Semaran', 'IMG-674b257a9a2be9.21559012.png', 'Kantor Kelurahan Kebun Agung', 3),
(536, 'KELURAHAN KEMIJEN', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Kemijen,+Ktr.+Kelurahan+Kemijen,+Jl.+Penjaringan+I+No.1,+Kemijen,+Semaran', 'IMG-674b25a7210bf5.62681332.png', 'Kantor Kelurahan Kemijen', 5),
(537, 'KELURAHAN MLATIBARU', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Mlatibaru,+Jl.+Mlatiharjo+Raya+No.16,+Mlatibaru,+Semarang+Timur,+Semarang', 'IMG-674b25da477021.73468549.png', 'Kantor Kelurahan Mlatibaru', 5),
(538, 'KELURAHAN MLATIHARJO', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Mlatiharjo,+Jl.+Citandui+Raya+III+No.2,+Mlatiharjo,+Semarang+Timur,+Semar', 'IMG-674b2605d94b67.15240596.png', 'Kantor Kelurahan Mlatiharjo', 5),
(539, 'KELURAHAN REJOMULYO', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Rejomulyo,+Jl.+Raden+Patah+No.176A,+Rejomulyo,+Semarang+Timur,+Semarang+C', 'IMG-674b26406cfec4.83182531.png', 'Kantor Kelurahan Rejomulyo', 5),
(540, 'KELURAHAN REJOSARI', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Rejosari,+Jl.+Kridangga+Raya+No.1,+Rejosari,+Semarang+Timur,+Semarang+Cit', 'IMG-674b2685e43860.47063017.png', 'Kantor Kelurahan Rejosari', 3),
(541, 'KELURAHAN SARIREJO', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/2C8M%2BH67+Kantor+Kelurahan+Sarirejo,+Jl.+Karangsono,+Sarirejo,+Kec.+Semarang+Tim.,+Kota+S', 'IMG-674b26c2cec8f6.83144254.png', 'Kantor Kelurahan Sarirejo', 2),
(542, 'KELURAHAN BANDARHARJO', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Bandarharjo,+Jl.+Bandarharjo+Selatan+Timur+No.17,+Bandarharjo,+Semarang+U', 'IMG-674b276c4c7710.03911079.png', 'Kantor Kelurahan Bandarharjo', 3),
(543, 'KELURAHAN BULU LOR', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Bulu+Lor,+Jl.+Surtikanti+No.27+B,+Bulu+Lor,+Kec.+Semarang+Utara,+Kota+Sem', 'IMG-674b28294354b5.36028212.png', 'Kantor Kelurahan Bulu Lor', 2),
(544, 'KELURAHAN DADAPSARI', 'https://www.google.com/maps/dir/Office+of+Communications+and+Information+Technology+Semarang,+2C87%2BGCX,+Sekayu,+Semarang+Tengah,+Semarang+City,+Central+Java+50132/Kantor+Kelurahan+Dadapsari,+Jl.+Kakap+No.72,+Dadapsari,+Kec.+Semarang+Utara,+Kota+Semarang', 'IMG-674b288081f4d0.26566903.png', 'Kantor Kelurahan Dadapsari', 3);

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `username`, `password`) VALUES
(4, 'admin', '$2y$10$oZmASnlq/YKoOkt.IT//mebTYVSM.oUnekI1LEzFg3mk5ysAm0cqy');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
